version: "3.1"

services:
  drupalweb:
    image: drupal
    ports:
      - '8080:80'

  postgresdb:
    image: postgres
    environment:
        POSTGRES_USER: boringnerd
        POSTGRES_PASSWORD: notthatsecretpassword
    